### ISSUE TITLE
This section does not describe if Session strips metadata from attachments.

### ISSUE THREAD

**Issue by DonW16** [oxen-io/oxen-website#50]
'Can I share attachments with my contacts? Does the app strip metadata from those attachments?' - https://getsession.org/faq

There is no metion of Session stripping metadata from attachments.

**Comment by yougotwill** [comment]
Hi @DonW16 thanks for bringing this to our attention! We have updated our FAQ to explain things better. 

See
https://getsession.org/faq#attachments
https://getsession.org/faq#attachment-metadata

Closing this issue.
