### ISSUE TITLE
http://oxen.io returns 404

### ISSUE THREAD

**Issue by fracting** [oxen-io/oxen-website#57]
Should redirect to https://oxen.io instead.

**Comment by fracting** [comment]
Reproduce this bug with a fresh browser without history caches.

**Comment by yougotwill** [comment]
@fracting What browser are you using? I can't recreate on my machine. I'm on macOS and tested in Chrome, Firefox and Safari.

**Comment by fracting** [comment]
The first time I found this bug was on a fresh installed Android Simulator with default browser

Then I found I can reproduce it with curl
```
 curl http://oxen.io
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.22.1</center>
</body>
</html>
```

I can also reproduce it with Brave Browser's privacy mode.

Does that help?

**Comment by yougotwill** [comment]
Interesting. Can recreate with curl. Will look into it. Thanks Qian!

**Comment by yougotwill** [comment]
@fracting I think I have fixed this issue. Would you mind testing for me please? 🙏

**Comment by fracting** [comment]
It's working for me with Brave Browser's privacy mode.

It's weird with curl, curl returns empty result for me, is that expected? I'm not a web developer and not sure what's the right behaviour.

```
curl -v http://oxen.io
*   Trying 172.67.146.128:80...
* Connected to oxen.io (172.67.146.128) port 80 (#0)
> GET / HTTP/1.1
> Host: oxen.io
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Date: Thu, 23 Feb 2023 00:17:23 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: max-age=3600
< Expires: Thu, 23 Feb 2023 01:17:23 GMT
< Location: https://oxen.io/
< Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=vwvcOqT3ZSiNYSSRuBjTbYn1lLju3fDSkmWV1VWM8V4RxqjxwkjZSQ12PmsOGb8qA3Z5mbZ0Bqr%2B43h8yDdb%2FerSaiFygw%2BVxTrewsrdKqPlVPHSCazHp2uP"}],"group":"cf-nel","max_age":604800}
< NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< Server: cloudflare
< CF-RAY: 79dbc7374ec455bd-SYD
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
<
* Connection #0 to host oxen.io left intact
```

**Comment by fracting** [comment]
Ah, I see, I need `curl -L http://oxen.io` to follow the redirection.

I think google is doing better:

```
curl http://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```

**Comment by yougotwill** [comment]
Not sure what Google has done differently but for now the redirection is working correctly. Can I consider this issue closed @fracting ?

**Comment by fracting** [comment]
It's interesting that http://getsession.com does the same thing like Google:

```
$ curl http://getsession.com
Redirecting to https://getsession.com/
```
So someone at the dev team must know how to configure it.

However, some other websites like http://facebook.com also don't show fallback content.
I have no preference, feel free to close the issue, thanks for the fix.

**Comment by yougotwill** [comment]
Our website is `getsession.org` 😂 But I appreciate your point. I agree that fallback content would be nice but for now I'll close this issue. Thanks for bringing it to my attention!

**Comment by fracting** [comment]
> Our website is `getsession.org` 😂 But I appreciate your point. I agree that fallback content would be nice but for now I'll close this issue. Thanks for bringing it to my attention!

😂😂😂😂😂😂
